#!/bin/sh

SYSTEM_STATE="$(systemctl is-system-running)"
FAILED_UNITS="$(systemctl list-units --failed --plain --no-legend | cut -d ' ' -f 1 | tr -s '[:space:]' ' ' | sed 's/ $//')"

case "$SYSTEM_STATE" in
	initializing|starting|running)
		echo "SYSTEMD OK: System is $SYSTEM_STATE"
		exit 0
		;;
	degraded|offline)
		echo "SYSTEMD CRITICAL: System is $SYSTEM_STATE ($FAILED_UNITS)"
		exit 2
		;;
	stopping|maintenance)
		echo "SYSTEMD WARNING: System is $SYSTEM_STATE"
		exit 1
		;;
esac

echo "SYSTEMD UNKNOWN: System is $SYSTEM_STATE"
exit 3
