#!/bin/sh
## Copyright © 2013 by Daniel Friesel <derf@derf.homelinux.org>
## License: WTFPL <http://sam.zoy.org/wtfpl>

WARN="${1}"
CRIT="${2}"

if [ -z "${1}" -o -z "${2}" ]; then
	exit 3
fi

TEMP=$(( $(cat /sys/class/thermal/thermal_zone0/temp) / 1000 ))

echo "cpu temperature: ${TEMP}"

if [ -z "${TEMP}" ]; then
	exit 3
fi

if [ "${TEMP}" -ge "${CRIT}" ]; then
	exit 2
fi

if [ "${TEMP}" -ge "${WARN}" ]; then
	exit 1
fi

exit 0
