#!/bin/sh
## Copyright © 2013 by Daniel Friesel <derf@derf.homelinux.org>
## License: WTFPL <http://sam.zoy.org/wtfpl>


PID_DOORD="$(pgrep -f /doord.py)"
OK_DOORD="$?"


if [ "$OK_DOORD" = "0" ]; then
	echo "OK: is running"
	exit 0
else
	echo "CRITICAL: not running - attempting restart"
	/usr/local/sbin/doord
	exit 2
fi
