#!/bin/bash

HOSTS=({backend,extern,frontend,shells,vm}.chaosdorf.de chaosdorf.dyndns.org)

for host in ${HOSTS[@]}; do
	echo -e "\n\t${host}"
	ssh -t root@${host} 'apt-get update && apt-get dist-upgrade'
done