#!/bin/sh

for host in backend extern frontend shells vm; do
	echo "\n\t${host}"
	ssh -t root@${host}.chaosdorf.de 'apt-get update && apt-get dist-upgrade'
done

ssh -t root@figurehead 'apt-get update && apt-get dist-upgrade'
