#!/bin/sh

set -e

KEYS='0x1D643B75'
HOST="$(hostname -f)"

backup_dpkg() {
	dpkg --get-selections > "/var/backups/external/${HOST}_packages"
}

backup_ldap() {
	slapcat \
	2> /dev/null \
	| gpg --encrypt --always-trust -r ${KEYS} \
	> "/var/backups/external/${HOST}_ldap.gpg"
}

backup_sql() {
	sh sqldump.sh \
	| gpg --encrypt --always-trust -r ${KEYS} \
	> "/var/backups/external/${HOST}_sql.gpg"
}

backup_tar() {
	tar --warning=no-file-ignored --warning=no-file-changed \
	-C / -cJf - "${1}" \
	| gpg --encrypt --always-trust -r ${KEYS} \
	> "/var/backups/external/${HOST}_${2}.tar.xz.gpg"
}

# Do not run *.chaosdorf.de backups simultaneously,
# omit this check when run manually.
# Also, do not run them between 03:00 and 04:00 because of DSL reconnect
# (we start at 00:03)
if [ ! -t 0 ]; then
	case "${HOST}" in
		backend.chaosdorf.de)      sleep 1h ;; # 01:03
		extern.chaosdorf.de)       sleep 2h ;; # 02:03
		figurehead.chaosdorf.dn42)          ;; # 00:03
		frontend.chaosdorf.de)     sleep 5h ;; # 05:03
		shells.chaosdorf.de)       sleep 4h ;; # 04:03
		vm.chaosdorf.de)                    ;; # 00:03
	esac
fi

mkdir /var/backups/external

backup_dpkg

backup_tar etc       etc
backup_tar root      root
backup_tar var/log   var_log
backup_tar usr/local usr_local
backup_tar var/local var_local

if [ "${HOST}" != figurehead.chaosdorf.dn42 ]; then
	backup_tar home home
	backup_tar srv  srv
fi

case "${HOST}" in

	backend.chaosdorf.de)
		backup_ldap
		;;

	frontend.chaosdorf.de)
		backup_tar var/mail var_mail
		backup_sql
		;;

	shells.chaosdorf.de)
		backup_tar var/spool/cron crontabs
		;;

esac

echo 'put /var/backups/external/* backup' \
| sftp -q -b - chaosdorf@aneurysm.derf0.net \
> /dev/null 2>&1

rm -r /var/backups/external

echo "${HOST}\tBackup\t0\tCompleted on $(date)" \
| send_nsca -H icinga.finalrewind.org \
> /dev/null

exit 0
