#!/bin/sh

read DOOR
read SHUTDOWN
read EVENT

cd /srv/www/de.chaosdorf/raumstatus

if [ "${SHUTDOWN}" = 1 ]; then
	STATEFILE=closed.png
elif [ "${DOOR}" = closed ]; then
	STATEFILE=private.png
elif [ "${DOOR}" = open ]; then
	if [ "${EVENT}" = 1 ]; then
		STATEFILE=open.png
	else
		STATEFILE=maybe_open.png
	fi
else
	STATEFILE=unknown.png
fi

if [ "$(readlink status.png)" != "${STATEFILE}" ]; then
	ln -sf $STATEFILE status.png
fi

cat > space_api.json.tmp
mv space_api.json.tmp space_api.json
