#!/bin/sh
# Make sure an MTA is not configured as open relay

FROM='foo@example.org'
TO='barz@example.org'

if [ -z "$1" ]; then
	echo 'NORELAY: Invalid invocation'
	exit 10
fi

OUT="$(swaks -S 2 -s "$1" -f "${FROM}" -t "${TO}")"

RET=${?}

case ${RET} in
	24)
		echo "NORELAY OK: ${OUT}"
		exit 0
	;;
	0)
		echo "NORELAY CRITICAL: Mail from ${FROM} to ${TO} accepted"
		exit 2
	;;
	*)
		echo "NORELAY UNKNOWN: ${OUT}"
		exit 3
	;;
esac
