#!/bin/sh

#%# family=auto
#%# capabilities=autoconf

if [ "$1" = "autoconf" ]; then
	echo yes
	exit 0
fi

if [ "$1" = "config" ]; then
    cat <<'EOF'
graph_title Online Hosts
graph_args -l 0
graph_vlabel Online Hosts
graph_category network
graph_info This graph shows the number of pingable hosts
hosts.label Online Hosts
hosts.draw LINE2
hosts.info Current number of online hosts
leases.label DHCP Leases
leases.draw LINE1
leases.info Current number of DHCP leases (both static and dynamic)
infra.label Critical Infrastructure
infra.draw AREA
infra.info Critical Infrastructure (Gateway, APs, Switches)
oinfra.label Other Infrastructure
oinfra.draw STACK
oinfra.info Other Infrastructure (Music, Printer)
virt.label Virtual
virt.draw STACK
virt.info Virtual Hosts on hyperion
dynip.label DHCP
dynip.draw STACK
dynip.info Guest hosts in DHCP range
static.label Static
static.draw STACK
static.info Hosts with a static (non-DHCP) IP
EOF
    exit 0
fi

HOSTS="$(fping -c 1 -g -i 10 172.22.26.0/24 2>&1 | fgrep '1/1/0%' | cut -d ' ' -f 1)"

NHOSTS="$(echo "$HOSTS" | wc -l)"
NCINFRA="$(echo "$HOSTS" | egrep -c '\.(1|2|3|4|7|9|10|93|94|95|96)$')"
NOINFRA="$(echo "$HOSTS" | egrep -c '\.(5|6|8|11|12|20|66|81|82)$')"
NVIRT="$(echo "$HOSTS" | egrep -c '\.(5.|60|61|77|103|128|155)$')"
NINFRA="$((NCINFRA + NOINFRA))"
NDHCP="$(echo "$HOSTS" | egrep -c '\.1?.?.$')"
NSTATIC="$(echo "$HOSTS" | egrep -c '\.2..$')"
LEASES="$( wc -l < /var/lib/misc/dnsmasq.leases)"

echo "hosts.value $NHOSTS"
echo "infra.value $NCINFRA"
echo "oinfra.value $NOINFRA"
echo "virt.value $NVIRT"
echo "dynip.value $((NDHCP - NINFRA - NVIRT))"
echo "static.value $NSTATIC"
echo "leases.value $LEASES"

echo "$HOSTS" > /tmp/.online_ips
echo "$((NDHCP - NINFRA - NVIRT))" > /tmp/.online_guests
echo "$LEASES" > /tmp/.dhcp_leases
chmod 644 /tmp/.online_ips
