Vagrant.configure("2") do |config|
  config.vm.box = "squeeze64"
  config.vm.box_url = "https://dl.dropbox.com/u/39133545/Publish/Vagrant/Provider/Vmware/vagrant-debian-squeeze64.box"

  config.vm.network :private_network, ip: "192.168.10.23"

  # The squeeze64 box used above has an outdated Puppet
  config.vm.provision :shell, inline: "wget http://apt.puppetlabs.com/puppetlabs-release-squeeze.deb && dpkg -i puppetlabs-release-squeeze.deb && apt-get update && apt-get install -y puppet"

  config.vm.provision :puppet do |puppet|
    puppet.module_path = "modules"
  end
end